DROP TABLE IF EXISTS ${env:IN_DATABASE_NAME}.${env:IN_TABLE_NAME};

CREATE EXTERNAL TABLE ${env:IN_DATABASE_NAME}.${env:IN_TABLE_NAME} (
    col1 STRING,
    col2 STRING
)
PARTITIONED BY
    (proc_date STRING)
ROW FORMAT DELIMITED
    FIELDS TERMINATED BY ','
    LINES TERMINATED BY   '\n'
STORED AS TEXTFILE
LOCATION
    '${env:IN_TBL_LOCATION}';
