DROP TABLE IF EXISTS ${env:SQOOP_TABLE};
CREATE EXTERNAL TABLE ${env:SQOOP_TABLE} (
    id int,
    col1 string
)
PARTITIONED BY (col2 string)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\001'
    LINES TERMINATED BY '\n'
    STORED AS TEXTFILE
LOCATION '${env:SQOOP_DIR}';

